global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'vm-nodes'
    static_configs:
      - targets: ['node-1:9100', 'node-2:9100']
